def create_conversation_name_from_message(content: str) -> str:
    """
    Creates a conversation name from the given content.

    The conversation name is generated by taking the first 30 characters
    of the content and appending '...' if the content is longer than 30 characters.

    Args:
        content (str): The content of the message.

    Returns:
        str: The generated conversation name.

    """
    return content[:30] + '...' if len(content) > 30 else content
